/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class FindDialogGUI extends javax.swing.JDialog {

    /**
     * Creates new form FindDialogGUI
     */
    public FindDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JButton getFindButton() {
        return findButton;
    }

    public void setFindButton(JButton findButton) {
        this.findButton = findButton;
    }

    public JButton getFindCancelButton() {
        return findCancelButton;
    }

    public void setFindCancelButton(JButton findCancelButton) {
        this.findCancelButton = findCancelButton;
    }

    public JRadioButton getFindDownDirectionBtn() {
        return findDownDirectionBtn;
    }

    public void setFindDownDirectionBtn(JRadioButton findDownDirectionBtn) {
        this.findDownDirectionBtn = findDownDirectionBtn;
    }

    public JCheckBox getFindMatchCaseCheckBox() {
        return findMatchCaseCheckBox;
    }

    public void setFindMatchCaseCheckBox(JCheckBox findMatchCaseCheckBox) {
        this.findMatchCaseCheckBox = findMatchCaseCheckBox;
    }

    public JTextField getFindPatternField() {
        return findPatternField;
    }

    public void setFindPatternField(JTextField findPatternField) {
        this.findPatternField = findPatternField;
    }

    public JRadioButton getFindUpDirectionBtn() {
        return findUpDirectionBtn;
    }

    public void setFindUpDirectionBtn(JRadioButton findUpDirectionBtn) {
        this.findUpDirectionBtn = findUpDirectionBtn;
    }

    public JCheckBox getFindWrapAroundCheckBox() {
        return findWrapAroundCheckBox;
    }

    public void setFindWrapAroundCheckBox(JCheckBox findWrapAroundCheckBox) {
        this.findWrapAroundCheckBox = findWrapAroundCheckBox;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        directionGroup = new javax.swing.ButtonGroup();
        findCancelButton = new javax.swing.JButton();
        findMatchCaseCheckBox = new javax.swing.JCheckBox();
        findWrapAroundCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        findUpDirectionBtn = new javax.swing.JRadioButton();
        findDownDirectionBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        findPatternField = new javax.swing.JTextField();
        findButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        findCancelButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        findCancelButton.setText("Cancel");

        findMatchCaseCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        findMatchCaseCheckBox.setText("Match case");

        findWrapAroundCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        findWrapAroundCheckBox.setText("Wrap around");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Direction", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        directionGroup.add(findUpDirectionBtn);
        findUpDirectionBtn.setText("Up");

        directionGroup.add(findDownDirectionBtn);
        findDownDirectionBtn.setSelected(true);
        findDownDirectionBtn.setText("Down");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(findUpDirectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(findDownDirectionBtn)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findUpDirectionBtn)
                    .addComponent(findDownDirectionBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Find what:");

        findPatternField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        findButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        findButton.setText("Find Next");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(findPatternField)
                        .addGap(18, 18, 18)
                        .addComponent(findButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(findWrapAroundCheckBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findMatchCaseCheckBox, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(findCancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(findPatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findCancelButton)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(findMatchCaseCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(findWrapAroundCheckBox)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FindDialogGUI dialog = new FindDialogGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup directionGroup;
    private javax.swing.JButton findButton;
    private javax.swing.JButton findCancelButton;
    private javax.swing.JRadioButton findDownDirectionBtn;
    private javax.swing.JCheckBox findMatchCaseCheckBox;
    private javax.swing.JTextField findPatternField;
    private javax.swing.JRadioButton findUpDirectionBtn;
    private javax.swing.JCheckBox findWrapAroundCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
