/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class ReplaceDialogGUI extends javax.swing.JDialog {

    /**
     * Creates new form ReplaceDialogGUI
     */
    public ReplaceDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JButton getReplaceAllBtn() {
        return replaceAllBtn;
    }

    public void setReplaceAllBtn(JButton replaceAllBtn) {
        this.replaceAllBtn = replaceAllBtn;
    }

    public JButton getReplaceBtn() {
        return replaceBtn;
    }

    public void setReplaceBtn(JButton replaceBtn) {
        this.replaceBtn = replaceBtn;
    }

    public JButton getReplaceCancelBtn() {
        return replaceCancelBtn;
    }

    public void setReplaceCancelBtn(JButton replaceCancelBtn) {
        this.replaceCancelBtn = replaceCancelBtn;
    }

    public JButton getReplaceFindNextBtn() {
        return replaceFindNextBtn;
    }

    public void setReplaceFindNextBtn(JButton replaceFindNextBtn) {
        this.replaceFindNextBtn = replaceFindNextBtn;
    }

    public JTextField getReplaceFindPatternField() {
        return replaceFindPatternField;
    }

    public void setReplaceFindPatternField(JTextField replaceFindPatternField) {
        this.replaceFindPatternField = replaceFindPatternField;
    }

    public JCheckBox getReplaceMatchCaseCheckBox() {
        return replaceMatchCaseCheckBox;
    }

    public void setReplaceMatchCaseCheckBox(JCheckBox replaceMatchCaseCheckBox) {
        this.replaceMatchCaseCheckBox = replaceMatchCaseCheckBox;
    }

    public JTextField getReplaceToPatternField() {
        return replaceToPatternField;
    }

    public void setReplaceToPatternField(JTextField replaceToPatternField) {
        this.replaceToPatternField = replaceToPatternField;
    }

    public JCheckBox getReplaceWrapAroundCheckBox() {
        return replaceWrapAroundCheckBox;
    }

    public void setReplaceWrapAroundCheckBox(JCheckBox replaceWrapAroundCheckBox) {
        this.replaceWrapAroundCheckBox = replaceWrapAroundCheckBox;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replaceCancelBtn = new javax.swing.JButton();
        replaceMatchCaseCheckBox = new javax.swing.JCheckBox();
        replaceWrapAroundCheckBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        replaceToPatternField = new javax.swing.JTextField();
        replaceBtn = new javax.swing.JButton();
        replaceAllBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        replaceFindPatternField = new javax.swing.JTextField();
        replaceFindNextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        replaceCancelBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replaceCancelBtn.setText("Cancel");

        replaceMatchCaseCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replaceMatchCaseCheckBox.setText("Match case");

        replaceWrapAroundCheckBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replaceWrapAroundCheckBox.setText("Wrap around");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Replace with:");

        replaceToPatternField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        replaceBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replaceBtn.setText("Replace");

        replaceAllBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replaceAllBtn.setText("Replace All");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Find what:");

        replaceFindPatternField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        replaceFindNextBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        replaceFindNextBtn.setText("Find Next");
        replaceFindNextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceFindNextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceFindPatternField)
                            .addComponent(replaceToPatternField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(replaceWrapAroundCheckBox)
                            .addComponent(replaceMatchCaseCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(replaceAllBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(replaceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(replaceFindNextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(replaceCancelBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(replaceFindPatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceFindNextBtn))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(replaceToPatternField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(replaceBtn))
                .addGap(18, 18, 18)
                .addComponent(replaceAllBtn)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(replaceCancelBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(replaceMatchCaseCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(replaceWrapAroundCheckBox))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void replaceFindNextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceFindNextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_replaceFindNextBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplaceDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplaceDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplaceDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplaceDialogGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ReplaceDialogGUI dialog = new ReplaceDialogGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton replaceAllBtn;
    private javax.swing.JButton replaceBtn;
    private javax.swing.JButton replaceCancelBtn;
    private javax.swing.JButton replaceFindNextBtn;
    private javax.swing.JTextField replaceFindPatternField;
    private javax.swing.JCheckBox replaceMatchCaseCheckBox;
    private javax.swing.JTextField replaceToPatternField;
    private javax.swing.JCheckBox replaceWrapAroundCheckBox;
    // End of variables declaration//GEN-END:variables
}
